name: Quality Assurance
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/quality-assurance.yml'
      - 'src/**'
      - 'pdns-etcd3.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  gocilint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
      - name: 'Set up Go (stable)'
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golang-ci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.8
  unit-tests:
    name: Unit tests (Go ${{ matrix.go }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21', '1.22', '1.23', '1.24', '1.25' ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
      - name: 'Set up Go (${{ matrix.go }})'
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - run: go test -tags unit -v ./src
  integration-tests-requests:
    name: Integration tests (Requests on ETCD ${{ matrix.etcd-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        etcd-version: ['3.2.32', '3.3.27', '3.4.40', '3.5.26', '3.6.7']
    env:
      ETCD_VERSION: ${{ matrix.etcd-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - run: go test -tags integration -count=1 -v -run Requests ./src
  integration-tests-pdns:
    name: Integration tests (PDNS ${{ matrix.pdns-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pdns-version: ['44', '45', '46', '47', '48', '49', '50', '51']
    env:
      PDNS_VERSION: ${{ matrix.pdns-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - run: go test -tags integration -count=1 -v -run PDNS ./src
